### ISSUE TITLE
Clarify documented behavior of --network option on single sites

### ISSUE THREAD

**Issue by gitlost** [wp-cli/cache-command#18]
Site transients are used on single sites as well as multisites so the name of the `--network` option and its description are a bit misleading.

The description of the `--network` option should be clarified.

One could also add `--site` as a synonym maybe. Edit: in this case deprecate `--network` by not mentioning it (although honour it for BC).

**Comment by danielbachhuber** [comment]
I don't have a strong preference one way or the other on this. Improving the description probably makes the most sense (solves the most immediate problem and has limited impact). 

Out of curiosity, how did you run into this?

**Comment by gitlost** [comment]
> how did you run into this?

Was trying to check the `update_plugins` transient on a single site.

**Comment by danielbachhuber** [comment]
@gitlost Do you have suggested text we should add to the documentation?

**Comment by gitlost** [comment]
Trying to come up with something but getting confused by the terminology and concept in WP core and that "site" was renamed "network" in https://core.trac.wordpress.org/ticket/28290 except it seems in this case. If I've got this straight:

1. For single sites, a site transient is just a transient with the prefix `_site_transient_` in the `wp_options` table. So a site transient is basically just a specially named transient.
2. For multisites, a site transient is a per-site entry with the prefix `_site_transient_` in the `wp_sitemeta` table. So a site transient varies depending on the current site, and in WP-CLI terms would be selected for a particular site using the `--url` global parameter.

Not sure how to convey that!
