### ISSUE TITLE
`wp cache flush [--network]` ignoring `alloptions`?

### ISSUE THREAD

**Issue by rask** [wp-cli/cache-command#25]
I had an issue with two sites living on same server under separate virtual hosts. I once accidentally muddled the other vhost resulting in both WP installations getting the same domain name into `siteurl`. I did all required fixes and it almost started working, until I noticed that accessing wp-admin on the previously muddled vhost kept redirecting to the other vhost.

I followed and found a call to `auth_redirect()` in `wp-admin/admin.php` which triggered this. It fetches the current `siteurl` option in some places. While the proper value was in the database `options` table, still the function attempts to redirect to the wrong vhost domain.

Then I saw that the old domain was in the `alloptions` cache while the database value was correct.

I tried `wp cache flush` and `wp cache flush --network`, but still `alloptions` contained the old and wrong domain in `siteurl`. The only thing that worked was `redis-cli flushall`.

The two sites are staging and production versions of a WP multisite application.

Is this a problem in the cache command or in the Redis cache backend? I can't see any code relating to `alloptions` in the Redis module (`object-cache.php`).

WP version is 4.9.1, WP-CLI version is 1.2.1. The server is a pretty regular Ubuntu 16.04 web server. We use a Redis3 installation (local) for object caching.

**Comment by rask** [comment]
Hmm I had an issue with Redis prefixes, but I would presume the command should flush caches anyways, are there clashing prefixes or not?

**Comment by danielbachhuber** [comment]
Hi @rask,

`wp cache flush` simply calls `wp_cache_flush()`, which is meant to drop the entire cache. If the latter doesn't, then this is a problem with your object cache implementation.
