### ISSUE TITLE
Allow multiple values for the delete command

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/cache-command#29]
I recently had the need to delete a long list of transients all at once. It would be great if the `wp [cache|transient] delete` command accepted multiple keys via multiple positional parameters.

**Comment by schlessera** [comment]
Currently, the signature for `cache delete` is this:

```
wp cache delete <key> [<group>]
```

So we'd need to decide how to handle the `[<group>]` positional argument then. Not sure we can reliably distinguish between these.

I think the safer bet is to use `xargs` or a similar shell tool for that...

**Comment by Nikschavan** [comment]
Now that we have [wp_cache_delete_multiple](https://developer.wordpress.org/reference/functions/wp_cache_delete_multiple/) in core, maybe we can add a separate command or support something like a comma-separated list of keys?
