### ISSUE TITLE
Respect network option with all option

### ISSUE THREAD

**Issue by pcfreak30** [wp-cli/cache-command#30]
It appears that if you want to delete all transients, it assumes `wp_options` (`$wpdb->options`) and not `wp_sitemeta` (Due to a early return). This needs refactoring.

Thanks.

**Comment by schlessera** [comment]
Yes, the command does not seem to be multisite-aware yet.

**Comment by ocean90** [comment]
Looks like I reported the same in #41 / #42.

**Comment by schlessera** [comment]
Yes, indeed. Can you add a corresponding "Fixes #30" to your PR description, @ocean90 ?
