### ISSUE TITLE
'transient' is not a registered wp command

### ISSUE THREAD

**Issue by syntax53** [wp-cli/cache-command#51]
WP CLI v2.1.0 transient command is non-existent.  Errors with 'transient' is not a registered wp command.

edit:  I had to run "wp package install git@github.com:wp-cli/cache-command.git" and it installed the package and then everything was working.  Documentation says this is supposed to be included already.  And I know packages are depreciated.

**Comment by schlessera** [comment]
I cannot replicate this:

<img width="642" alt="image 2019-03-04 at 6 37 04 pm" src="https://user-images.githubusercontent.com/83631/53751436-8947ec80-3eac-11e9-93f2-4406eb4ddf64.png">

Could it be that you already had a conflicting package installed prior to adding the cache command?

**Comment by danielbachhuber** [comment]
@syntax53 Can you share the installation instructions you've followed? You might've installed `wp-cli/wp-cli` when you wanted `wp-cli/wp-cli-bundle`.

**Comment by syntax53** [comment]
It would appear that is exactly the case.
