### ISSUE TITLE
Error in "Delete all transients in a multsite" example

### ISSUE THREAD

**Issue by priscillamc** [wp-cli/cache-command#60]
Example is showing &amp;&amp; instead of &&:
``$ wp transient delete --all --network &amp;&amp; wp site list --field=url | xargs -n1 -I % wp --url=% transient delete --all``

Should be:
``$ wp transient delete --all --network && wp site list --field=url | xargs -n1 -I % wp --url=% transient delete --all``

**Comment by danielbachhuber** [comment]
From https://developer.wordpress.org/cli/commands/transient/delete/#examples

I guess we have a bug in the markdown parser or something 😞

**Comment by danielbachhuber** [comment]
🔨
