### ISSUE TITLE
Add support for wp_cache_supports

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/cache-command#79]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

In WordPress 6.1, a new function function was added called wp_cache_supports. This function takes a string parameter and returns a Boolean. This function is used to determine if the current object cache supports a feature, like multiple get. 

**Describe the solution you'd like**

A new command. 

WP cache supports `<feature>`

This would return a bool as it's output.

**Comment by janw-me** [comment]
@spacedmonkey Can you specifically check the documentation/comments.
As I don't fully understand the use case.
I see the original [wp_cache_supports](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/cache.php#L314) and see a static list, it doesn't seem extenable?
I'm guessing caching plugins override this function?

**Comment by tillkruss** [comment]
Correct they do, or fallback to core' function.
