### ISSUE TITLE
Add support for `wp_cache_flush_group`

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/cache-command#80]
## Feature Request

In WordPress 6.1, `wp_cache_flush_group` was added to core. See blog [post](https://make.wordpress.org/core/2022/10/11/performance-field-guide-for-wordpress-6-1/). 

This function, allows for developers to clear all keys in a cache group, instead of one key at a time. 

**Describe the solution you'd like**

Create a new command that allows for the `wp_cache_flush_group` function to be called, like so

`wp cache clear group <group>`

Before calling this function, if should check if the object cache support this functionality, by calling `wp_cache_supports` and fail fast if the current object cache doesn't support this functionality.

**Comment by janw-me** [comment]
@spacedmonkey Again I'd like your opinion on this.

But now I also need extra help with for the tests. How can I remove support for `flush_group` because I can't test is properly right now.

**Comment by tillkruss** [comment]
>How can I remove support for flush_group because I can't test is properly right now.

I don't think you can? `wp_cache_flush_group()` will either be defined as a fallback by WP, or by an object caching plugin.

Calling `wp_cache_supports()` will tell you whether the 3rd party plugin supports it, or if the core fallback is used to flush the entire cache.

**Comment by janw-me** [comment]
Within the behat test we can install plugins, or add extra php code.
So it's possible. Installing a regular plugin isn't ideal, because test might fail when that plugin changes.

So if we can create a single file (and small) plugin. We could create & activate that during the tests.
